import type { Caterer } from './types';

export const caterers: Caterer[] = [
  {
    id: '1',
    name: 'The Royal Kitchen',
    city: 'Jaipur',
    specialty: ['North Indian', 'Wedding'],
    pricePerPlate: 2500,
    rating: 4.8,
    imageUrl: 'https://picsum.photos/seed/caterer1/400/300',
    imageHint: 'indian food',
    contact: { phone: '9876543210', email: 'contact@royalkitchen.com' },
    description: 'Experience the taste of royalty with our authentic Rajasthani and North Indian cuisine. Perfect for lavish weddings and grand celebrations.',
    reviews: [
      { id: 'r1', author: 'Priya S.', rating: 5, comment: 'Absolutely amazing food and service! They made our wedding unforgettable.', date: '2023-10-15' },
      { id: 'r2', author: 'Amit G.', rating: 4.5, comment: 'Great food, professional staff. Highly recommended.', date: '2023-09-20' },
    ],
  },
  {
    id: '2',
    name: 'Coastal Flavors',
    city: 'Mumbai',
    specialty: ['South Indian', 'Continental'],
    pricePerPlate: 1800,
    rating: 4.6,
    imageUrl: 'https://picsum.photos/seed/caterer4/400/300',
    imageHint: 'south indian',
    contact: { phone: '9988776655', email: 'info@coastalflavors.in' },
    description: 'Bringing the authentic tastes of the coast to your event. We specialize in seafood, and traditional South Indian delicacies.',
    reviews: [
      { id: 'r3', author: 'Rohan M.', rating: 5, comment: 'The seafood was incredibly fresh and delicious. Best caterers in Mumbai!', date: '2023-11-01' },
    ],
  },
  {
    id: '3',
    name: 'Metropolitan Events',
    city: 'Delhi',
    specialty: ['Corporate', 'Italian', 'Chinese'],
    pricePerPlate: 2200,
    rating: 4.7,
    imageUrl: 'https://picsum.photos/seed/caterer3/400/300',
    imageHint: 'corporate event',
    contact: { phone: '9123456789', email: 'events@metro.com' },
    description: 'Professional and chic catering solutions for corporate events, conferences, and formal gatherings. Global cuisine with a modern twist.',
    reviews: [
      { id: 'r4', author: 'Sunita K.', rating: 5, comment: 'Impeccable service for our annual conference. The food was a huge hit.', date: '2023-10-25' },
      { id: 'r5', author: 'Vikram B.', rating: 4, comment: 'Good variety and presentation.', date: '2023-08-12' },
    ],
  },
  {
    id: '4',
    name: 'Garden City Caterers',
    city: 'Bangalore',
    specialty: ['Continental', 'Wedding', 'Desserts'],
    pricePerPlate: 3000,
    rating: 4.9,
    imageUrl: 'https://picsum.photos/seed/caterer2/400/300',
    imageHint: 'wedding catering',
    contact: { phone: '9876501234', email: 'hello@gardencity.com' },
    description: 'Elegant and sophisticated catering for the modern palate. We focus on fresh, local ingredients and beautiful presentation.',
    reviews: [
      { id: 'r6', author: 'Ananya R.', rating: 5, comment: 'They created a fairytale wedding for us. The dessert bar was out of this world!', date: '2023-11-10' },
      { id: 'r7', author: 'Rajesh P.', rating: 5, comment: 'Truly premium service.', date: '2023-09-05' },
    ],
  },
  {
    id: '5',
    name: 'Sweet Moments',
    city: 'Pune',
    specialty: ['Desserts', 'Italian'],
    pricePerPlate: 1200,
    rating: 4.5,
    imageUrl: 'https://picsum.photos/seed/caterer5/400/300',
    imageHint: 'appetizers platter',
    contact: { phone: '9988771122', email: 'orders@sweetmoments.co' },
    description: 'Specializing in gourmet desserts, pastries, and Italian snacks. Perfect for birthdays, high-teas, and smaller gatherings.',
    reviews: [
       { id: 'r8', author: 'Meera D.', rating: 4.5, comment: 'The tiramisu was divine! A bit pricey but worth it for special occasions.', date: '2023-11-05' },
    ],
  },
  {
    id: '6',
    name: 'Kolkata Classics',
    city: 'Kolkata',
    specialty: ['North Indian', 'Chinese'],
    pricePerPlate: 1500,
    rating: 4.4,
    imageUrl: 'https://picsum.photos/seed/caterer6/400/300',
    imageHint: 'chef cooking',
    contact: { phone: '9555666777', email: 'support@kolkataclassics.com' },
    description: 'Authentic Bengali cuisine and popular Indo-Chinese dishes that capture the heart of Kolkata\'s food culture.',
    reviews: [
      { id: 'r9', author: 'Arijit B.', rating: 4, comment: 'Good traditional food. The fish curry was excellent.', date: '2023-10-02' },
    ],
  },
];

export { CITIES_IN_INDIA, SPECIALTIES } from './types';
