"use client";

import { useState } from 'react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { generateMenu } from '@/ai/flows/generate-menu-flow';
import type { GenerateMenuOutput } from '@/ai/flows/generate-menu-flow';
import { Wand2, Loader2 } from 'lucide-react';

export default function GenerateMenu({ specialties }: { specialties: string[] }) {
  const [menu, setMenu] = useState<GenerateMenuOutput | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isOpen, setIsOpen] = useState(false);

  const handleGenerateMenu = async () => {
    setIsLoading(true);
    setMenu(null);
    try {
      const result = await generateMenu({ specialties });
      setMenu(result);
    } catch (error) {
      console.error('Failed to generate menu:', error);
      // Optionally, show an error message to the user
    } finally {
      setIsLoading(false);
    }
  };

  const handleOpenChange = (open: boolean) => {
    setIsOpen(open);
    if (open && !menu && !isLoading) {
      handleGenerateMenu();
    }
  }

  return (
    <Dialog open={isOpen} onOpenChange={handleOpenChange}>
      <DialogTrigger asChild>
        <Button variant="outline" className="w-full">
          <Wand2 className="mr-2 h-4 w-4" />
          Generate Sample Menu
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[625px]">
        <DialogHeader>
          <DialogTitle className="font-headline">AI-Generated Sample Menu</DialogTitle>
          <DialogDescription>
            Here's a sample menu generated by AI based on the caterer's specialties.
          </DialogDescription>
        </DialogHeader>
        <div className="max-h-[60vh] overflow-y-auto p-1 pr-4">
          {isLoading && (
            <div className="flex items-center justify-center py-12">
              <Loader2 className="h-8 w-8 animate-spin text-primary" />
              <p className="ml-4 text-muted-foreground">Generating your menu...</p>
            </div>
          )}
          {menu && (
            <div className="space-y-6">
              {menu.menu.map((section) => (
                <div key={section.specialty}>
                  <h3 className="font-headline text-xl font-bold text-primary mb-3">{section.specialty}</h3>
                  <div className="space-y-3">
                    {section.items.map((item) => (
                      <div key={item.name} className="p-3 bg-card rounded-md border">
                        <p className="font-semibold">{item.name}</p>
                        <p className="text-sm text-muted-foreground">{item.description}</p>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
